* Fonones y espectroscopía Raman en semiconductores bidimensionales

* Objectivos del trabajo propuesto

Los materiales bidimensionales (2D) como el grafeno son de gran interés tanto por sus propiedades físicas exclusivas como por sus aplicaciones potenciales. El estudio de la dinámica de la red cristalina (fonones) de estos materiales es un requisito previo para entender su estabilidad estructural y propiedades térmicas, así como sus propiedades de transporte y ópticas.

Este Trabajo de Fin de Grado consiste en la computación de los modos vibracionales de materiales semiconductores 2D y su correlación con los observables relevantes para la interpretación de los experimentos de dispersión de luz.

El estudiante trabajará la bibliografía pertinente para documentarse sobre el estado de arte teórico, y aprenderá una metodología de cálculo basada en la aproximación armónica a la dinámica de una red bidimensional. Seguidamente, el estudiante implementará un modelo de constantes de fuerza para calcular los modos vibracionales de un material 2D modelo. Seguidamente podran determinarse los modos vibracionales activos Raman.

Este trabajo está diseñado especialmente para estudiantes interasados en programación usando lenguages avanzados tipo Python, siempre orientados a aplicar lo aprendido en las asignaturas de Mecánica Cuántica o Física de Estado Sólido.
